/**
 * Generate the service worker after a build.
 *
 * Written from the real contents of dist/ rather than by a plugin: the precache
 * list is then exactly what shipped, and the cache name is a hash of it, so a
 * deploy that changes one byte invalidates the old cache and a deploy that
 * changes nothing does not.
 *
 *   node tools/gen-sw.mjs      (runs as part of `npm run build`)
 */

import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DIST = join(ROOT, "dist");

/** Source maps are for developers, not for a tablet's offline cache. */
const SKIP = /\.map$/;

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const files = walk(DIST)
  .filter((f) => !SKIP.test(f))
  .map((f) => "./" + relative(DIST, f).split("\\").join("/"))
  .filter((f) => f !== "./sw.js")
  .sort();

const hash = createHash("sha256");
for (const f of files) hash.update(readFileSync(join(DIST, f.slice(2))));
const version = hash.digest("hex").slice(0, 12);

const sw = `/* Generated by tools/gen-sw.mjs — do not edit. */
const CACHE = "frosmo-${version}";
const ASSETS = ${JSON.stringify(files, null, 2)};

self.addEventListener("install", (event) => {
  // The whole app is a few tens of kilobytes, so it is precached in one go and
  // every later visit is offline-capable, including the first one after
  // install-to-home-screen.
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" || new URL(request.url).origin !== self.location.origin) return;

  // Navigations go to the network first so a deploy is picked up on the next
  // launch, and fall back to the cached shell when there is no network — which,
  // for a device on a stand in a kitchen, is the common case.
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          void caches.open(CACHE).then((cache) => cache.put("./index.html", copy));
          return response;
        })
        .catch(() => caches.match("./index.html").then((r) => r ?? Response.error())),
    );
    return;
  }

  // Everything else is content-hashed by the build, so a cache hit is always
  // correct and always the fastest answer.
  event.respondWith(
    caches.match(request).then(
      (hit) =>
        hit ??
        fetch(request).then((response) => {
          if (response.ok) {
            const copy = response.clone();
            void caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        }),
    ),
  );
});
`;

writeFileSync(join(DIST, "sw.js"), sw);
console.log(`sw.js: ${files.length} assets, cache frosmo-${version}`);
